<a href="https://colab.research.google.com/github/TenGiCungDuocMa/ML_2024_21130536_Tran_Bui_Quoc_Thang/blob/main/Lab1_21130536_TranBuiQuocThang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1. Python Programming


Task 1.1

In [31]:
#task1_1
def task1_1():
  n = int(input('Enter n= '))
  l = []
  for i in range(n):
    l.append(int(input('Enter = ')))
  l.sort()
  print('Min element in L is: ',l[0])
  l.reverse()
  print('Max element in L is: ',l[0])
  sumL = sum(l)
  print('Sum of l is: ',sumL)
  l.reverse()
  countPosNum = 0
  countNegNum = 0
  for number in l:
    if(number == 0):
      continue
    if (number> 0):
      countPosNum += 1
    else:
      countNegNum += 1
  print('The total number of positive numbers is:',countPosNum)
  print('The total number of negative numbers is:',countNegNum)
task1_1()

Enter n= 10
Enter = 1
Enter = 3
Enter = -1
Enter = -3
Enter = 6
Enter = 8
Enter = 4
Enter = 2
Enter = 0
Enter = 0
Min element in L is:  -3
Max element in L is:  8
Sum of l is:  20
The total number of positive numbers is: 6
The total number of negative numbers is: 2


Task 1.2

In [ ]:
#task1_2
def factorial(n):
  if (n == 0):
    return 1
  return n*factorial(n-1)

def task1_2(total,n):
  if (n < 2):
    return total + 1
  else:
    return task1_2(total,n-1) + factorial(n)

s = task1_2(0,99)
print(s)

942786239765826579160595268206839381354754349601050974345395410407078230249590414458830117442618180732911203520208889371641659121356556442336528920420940313


Task 1.3

In [4]:
#task1_3
#create class Account
class Account:
  def __init__(selt, name, email, country):
    selt._name = name
    selt._email = email
    selt._country = country
    selt._friends = []
    selt._posts = []

  def getName(selt):
    return selt._name

  def getFriends(selt):
    return selt._friends

  def getPosts(selt):
    return selt._posts

  def getCountry(selt):
    return selt._country

  def toString(selt):
    return selt._name + ', ' + selt._email + ', ' + selt._country + ', '
    + selt._friends+ ', ' + selt._posts

  def getMaxLikePostByFriend(selt):
    maxlike = -10
    accountHasMaxLike = None
    for f in selt._friends:
      for p in f.getPosts():
        if(p.getLikes() > maxlike):
          maxlike = p.getLikes()
          accountHasMaxLike = f
        else:
          maxlike = maxlike
    return accountHasMaxLike

#create class VerifiedAccount
class VerifiedAccount(Account):
  def __init__(selt, name, email, country,fromDate):
    super().__init__(name,email,country)
    selt.__fromDate = fromDate

class NormalProduct(Account):
  def __init__(selt, name, email, country):
    super().__init__(name,email,country)

#create class Post
class Post:
  def __init__(selt, content, subject, likes):
    selt.__content = content
    selt.__subject = subject
    selt.__likes = likes
  def getLikes(selt):
    return selt.__likes

#create class
class AccountManager():
  def __init__(selt):
    selt.__accounts = []

  def getAccounts(selt):
    return selt.__accounts

  def groupAccountsByPostLike(selt):
    d = {}
    for acc in selt.__accounts:
      if (len(acc.getPosts()) < 10):
        d[False]= acc
      else:
        d[True] = acc
    return d

  def filterAccounts(selt,country):
    listset = []
    for acc in selt.__accounts:
      if (acc.getCountry() == country):
        listset.append(acc)
    res = sorted(listset, reverse=True, key=lambda ac : len(ac.getPosts()))
    result = sorted(res, key=lambda ac: ac.getName())
    return result

#test
post1 = Post('sang nay an gi', 'sang nay an khoai lang luoc',200000)
post2 = Post('trua nay an gi', 'trua nay an hu tieu',5000)
post3 = Post('chieu nay an gi', 'chieu nay an banh xeo',4000)
post4 = Post('toi nay an gi', 'toi nay an kem',300000)
post5 = Post('sang mai an gi', 'sang mai an com',15000)
post6 = Post('trua mai an gi', 'trua mai an banh canh',90)
post7 = Post('chieu mai an gi', 'chieu mai an bun',3010)
post8 = Post('toi mai an gi', 'toi mai an mi tom',900000000)
post9 = Post('toi nay uong gi', 'toi nay uong ca phe',455600)
post10 = Post('sang nay uong gi', 'sang nay uong tra sua',1000)

acc1 = VerifiedAccount('tran bui quoc thang', '123@gmail.com', 'VN', '10/2/2024')
acc2 = VerifiedAccount('tran quoc thang', '123asdf@gmail.com', 'VN','9/3/2022')
acc3 = NormalProduct('tran thang', 'xcvb123@gmail.com', 'USA')

acc1.getFriends().append(acc2)
acc1.getFriends().append(acc3)
acc1.getPosts().append(post1)
acc1.getPosts().append(post2)
acc1.getPosts().append(post3)
acc1.getPosts().append(post4)
acc1.getPosts().append(post5)
acc1.getPosts().append(post6)
acc1.getPosts().append(post7)
acc1.getPosts().append(post8)
acc1.getPosts().append(post9)
acc1.getPosts().append(post10)

acc2.getFriends().append(acc3)
acc2.getFriends().append(acc1)
acc2.getPosts().append(post2)
acc2.getPosts().append(post4)
acc2.getPosts().append(post6)
acc2.getPosts().append(post7)
acc2.getPosts().append(post8)
acc2.getPosts().append(post10)

acc3.getFriends().append(acc1)
acc3.getFriends().append(acc2)
acc3.getPosts().append(post4)
acc3.getPosts().append(post3)
acc3.getPosts().append(post5)
acc3.getPosts().append(post7)
acc3.getPosts().append(post8)
acc3.getPosts().append(post9)
acc3.getPosts().append(post1)

print('Get Max Like Post By Friend:')
print(acc1.getMaxLikePostByFriend().toString())
print(acc2.getMaxLikePostByFriend().toString())
print(acc3.getMaxLikePostByFriend().toString())

accmana = AccountManager()
accmana.getAccounts().append(acc2)
accmana.getAccounts().append(acc3)
accmana.getAccounts().append(acc1)

print('----------------------------------')
print('Group Account By Post Like:')
for key,value in accmana.groupAccountsByPostLike().items():
  print(key,':',value.toString())

print('----------------------------------')
print('Filter Accounts:')
for i in accmana.filterAccounts('VN'):
  print(i.toString())

Get Max Like Post By Friend:
tran quoc thang, 123asdf@gmail.com, VN, 
tran thang, xcvb123@gmail.com, USA, 
tran bui quoc thang, 123@gmail.com, VN, 
----------------------------------
Group Account By Post Like:
False : tran thang, xcvb123@gmail.com, USA, 
True : tran bui quoc thang, 123@gmail.com, VN, 
----------------------------------
Filter Accounts:
tran bui quoc thang, 123@gmail.com, VN, 
tran quoc thang, 123asdf@gmail.com, VN, 


Task 2. NumPy API

Task 2.1

In [21]:
#Task 2.1
import numpy as np

x = np.arange(10,26)
x = x[::-1]
print(x)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 2.2

In [18]:
#task 2.2
import numpy as np

def task2_2(array,n):
  return np.tile(array,n)

#test
array = [1, 2, 3, 4]
print(task2_2(array,2))
print(task2_2(array,3))

[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


Task 2.3

In [34]:
import numpy as np

def task2_3(arr, specValue):
  for row in arr:
    row[row > specValue] = specValue
  return arr

#test
x =np.array([ [ 0.42, 0.48, 0.32],
              [ 0.74, 0.58, 0.38],
              [ 0.51, 0.34, 0.15] ])

print(task2_3(x,0.5))


[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
